#!/bin/bash

#SBATCH --job-name=preprocess   # Job name
#SBATCH --output=logs/pd_train_job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --gres=gpu               # Schedule a GPU, or more with gpu:2 etc
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the Red or Brown queue
#SBATCH --mail-type=FAIL,END


module load Anaconda3
source activate multi-gpu
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"